apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: usernames
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000   # 7 days
